### ISSUE TITLE
build不通过。

### ISSUE THREAD

**Issue by Gale-Gao** [Dreamacro/clash-dashboard#26]
本项目于Docker中node镜像创建的容器中，无法通过npm run build构建，且使用npm start运行也会出错。
以下为构建日志输出，本Issue中未写入npm start的记录。

bash# npm run build

> clash-dashboard@0.1.0 build /root/clash-dashboard
> npm run clean-dist && NODE_ENV=production webpack --config=configs/webpack/prod.js

> clash-dashboard@0.1.0 clean-dist /root/clash-dashboard
> rm -rf dist

ℹ ｢atl｣: Using typescript@3.8.3 from typescript
ℹ ｢atl｣: Using tsconfig.json from /root/clash-dashboard/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Time: 16142ms
Hash: 15534b70c53c1ad2d095
Version: webpack 4.42.1
Time: 89492ms
Built at: 04/06/2020 2:55:56 PM
 4 assets
Entrypoint main = js/1.bundle.15534b70c53c1ad2d095.min.js main.15534b70c53c1ad2d095.css js/bundle.15534b70c53c1ad2d095.min.js
  [7] ./stores/index.ts 182 bytes {0} [built]
  [9] ./lib/request.ts 8.8 KiB {0} [built]
 [11] ./lib/jsBridge.ts 2.56 KiB {0} [built]
 [24] ../node_modules/react-router-dom/esm/react-router-dom.js + 6 modules 69.9 KiB {1} [built]
      |    7 modules
 [41] ./containers/Proxies/index.tsx 3.53 KiB {0} [built]
 [48] ./index.ts 342 bytes {0} [built]
 [49] ./render.tsx 807 bytes {0} [built]
 [58] ./stores/HookStore.ts 6.54 KiB {0} [built]
[125] ./containers/App.tsx 2.28 KiB {0} [built]
[127] ./containers/App.scss 39 bytes {0} [built]
[171] ./containers/Logs/index.tsx 3.8 KiB {0} [built]
[173] ./containers/Rules/index.tsx 1.76 KiB {0} [built]
[176] ./containers/Settings/index.tsx 9.2 KiB {0} [built]
[178] ./containers/Sidebar/index.tsx 1.15 KiB {0} [built]
[181] ./containers/Connections/index.tsx 8.23 KiB {0} [built]
    + 203 hidden modules

ERROR in ./assets/logo.png
Module build failed (from ../node_modules/image-webpack-loader/index.js):
Error: 
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 @ ./containers/Sidebar/index.tsx 1:573-600
 @ ./containers/App.tsx
 @ ./render.tsx
 @ ./index.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! clash-dashboard@0.1.0 build: `npm run clean-dist && NODE_ENV=production webpack --config=configs/webpack/prod.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the clash-dashboard@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-06T14_55_56_763Z-debug.log

**Comment by Dreamacro** [comment]
plz use `npm ci` instead of `npm install`

**Comment by Gale-Gao** [comment]
> plz use `npm ci` instead of `npm install`

Succeed.

Thank you very much.
