### ISSUE TITLE
报错，怎么解决

### ISSUE THREAD

**Issue by lamu0102** [Dreamacro/clash-dashboard#46]
ERROR in ./assets/logo.png
Module build failed (from ../node_modules/image-webpack-loader/index.js):
Error: Cannot find module 'pngquant-bin'
Require stack:
- /root/clash-dashboard/node_modules/imagemin-pngquant/index.js
- /root/clash-dashboard/node_modules/image-webpack-loader/index.js
- /root/clash-dashboard/node_modules/loader-runner/lib/loadLoader.js
- /root/clash-dashboard/node_modules/loader-runner/lib/LoaderRunner.js
- /root/clash-dashboard/node_modules/webpack/lib/NormalModule.js
- /root/clash-dashboard/node_modules/webpack/lib/NormalModuleFactory.js
- /root/clash-dashboard/node_modules/webpack/lib/Compiler.js
- /root/clash-dashboard/node_modules/webpack/lib/webpack.js
- /root/clash-dashboard/node_modules/webpack-cli/bin/utils/validate-options.js
- /root/clash-dashboard/node_modules/webpack-cli/bin/utils/convert-argv.js
- /root/clash-dashboard/node_modules/webpack-cli/bin/cli.js
- /root/clash-dashboard/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (/root/clash-dashboard/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/root/clash-dashboard/node_modules/imagemin-pngquant/index.js:5:18)
    at Module._compile (/root/clash-dashboard/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (/root/clash-dashboard/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.module.exports (/root/clash-dashboard/node_modules/image-webpack-loader/index.js:72:20)
 @ ./containers/Sidebar/index.tsx 1:996-1023
 @ ./containers/App.tsx
 @ ./render.tsx
 @ ./index.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! clash-dashboard@0.1.0 build: `npm run clean-dist && NODE_ENV=production webpack --config=configs/webpack/prod.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the clash-dashboard@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-22T08_28_18_183Z-debug.log

**Comment by Dreamacro** [comment]
如果不知道怎么构建一个前端项目，直接下载 https://github.com/Dreamacro/clash-dashboard/archive/gh-pages.zip
